# Disabled cache in hope of improving reliability of AppVeyor builds
#cache:
#- "c:\\sr" # stack root, short paths == fewer problems

build: off

before_test:
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
platform: x64
os: MinGW
environment:
  OPENSSL_VERSION: 1_1_0c
  global:
    STACK_ROOT: "c:\\sr"

install:
  - ps: Start-FileDownload "http://slproweb.com/download/Win32OpenSSL-${env:OPENSSL_VERSION}.exe"
  - cmd: Win32OpenSSL-%OPENSSL_VERSION%.exe /silent /verysilent /sp- /suppressmsgboxes
  - cmd: SET OPENSSL_LIB_DIR=C:\OpenSSL-Win32
  - cmd: SET OPENSSL_INCLUDE_DIR=C:\OpenSSL-Win32\include

test_script:
  - stack setup > nul
  - echo "" | stack --no-terminal test
